### ISSUE TITLE
Is it possible to extend the code to accept padding masks?

### ISSUE THREAD

**Issue by KatarinaYuan** [berlino/gated_linear_attention#3]
Hi, thank you for this interesting work. Wondering if it's possible to extend the currently public code to accept padding masks as augments? Thank you for the help!

**Comment by sustcsonglin** [comment]
Yep! I can implement this within a few day.

**Comment by KatarinaYuan** [comment]
Thank you so much for helping! Looking forward to that!

**Comment by sustcsonglin** [comment]
Hello, i wonder what kind of padding mask do you need? The model only supports causal linear attention
