### ISSUE TITLE
A Full LM class

### ISSUE THREAD

**Issue by Cranial-XIX** [berlino/gated_linear_attention#4]
Hi,

Thanks for this great work! I wonder if you could provide a wrapper for a full language model class, like in Mamba and RetNet they have `MambaLMHeadModel` and `RetNetDecoder`. Thanks a lot!

**Comment by berlino** [comment]
Thanks for your interests!

Yes, we plan to add the model file soon.

**Comment by berlino** [comment]
I've added a model class in gla_model.py, let me if there is any further questions
