### ISSUE TITLE
How to get St？

### ISSUE THREAD

**Issue by Joluck** [berlino/gated_linear_attention#6]
![image](https://github.com/berlino/gated_linear_attention/assets/139205286/e4122d60-24bf-4557-b8b9-8f31aea38ce0)

I wanted to get St but I couldn't find his exact location, I returned memory_cache but he doesn't seem to be equal to St

**Comment by sustcsonglin** [comment]
Hi, we didn't include the recurrent form of the model. If you need this feature we will consider adding it soon. Our code is chunkwise, i..e, storing the hidden state of the last element for a single contiguous chunk.

**Comment by Joluck** [comment]
> Hi, we didn't include the recurrent form of the model. If you need this feature we will consider adding it soon. Our code is chunkwise, i..e, storing the hidden state of the last element for a single contiguous chunk.

Thanks，because I need to infer, I require the final hidden state. And I want know what memory_cache is.
![image](https://github.com/berlino/gated_linear_attention/assets/139205286/e7dca7c3-8f50-4f54-84e2-56a05df2a744)

**Comment by sustcsonglin** [comment]
i will add an interface to obtain the final hidden state soon.

**Comment by Joluck** [comment]
> i will add an interface to obtain the final hidden state soon.

Thank you so much

**Comment by sustcsonglin** [comment]
Hi, you can check out [impl1](https://github.com/sustcsonglin/flash-linear-attention/blob/main/fla/ops/triton/gla/chunk_fuse.py#L477C1-L491C13) and [impl2](https://github.com/sustcsonglin/flash-linear-attention/blob/main/fla/ops/triton/gla/recurrent_fuse.py#L290C1-L298C13) to obtain the final hidden state.

**Comment by Joluck** [comment]
> Hi, you can check out [impl1](https://github.com/sustcsonglin/flash-linear-attention/blob/main/fla/ops/triton/gla/chunk_fuse.py#L477C1-L491C13) and [impl2](https://github.com/sustcsonglin/flash-linear-attention/blob/main/fla/ops/triton/gla/recurrent_fuse.py#L290C1-L298C13) to obtain the final hidden state.

超感谢，上周我学了一点triton就自己写了last state测试没有什么问题，现在正好可以学习一下你怎么写的初始化state。对了还有个问题，就是intra部分会在块间在分块最小t需要满足16的倍数，所以目前推理的时候需要pad计算的时候需要mask，我感觉pad有些浪费不知道你有没有好的解决办法

**Comment by sustcsonglin** [comment]
你的推理指的是什么？ 是自回归推理 还是 eval一下给定句子的PPL?  目前感觉Pad到16的倍数不是很cost，所以暂时还没有给GLA加内部的padding机制（需要改cuda kernel有点麻烦）。retnet的实现倒是在triton kernel里面加了mask的机制，所以不需要pad。

**Comment by Joluck** [comment]
> 你的推理指的是什么？ 是自回归推理 还是 eval一下给定句子的PPL? 目前感觉Pad到16的倍数不是很cost，所以暂时还没有给GLA加内部的padding机制（需要改cuda kernel有点麻烦）。retnet的实现倒是在triton kernel里面加了mask的机制，所以不需要pad。

都有，推理目前没有区分块。还有个问题是，我测试chunksize的时候发现chunk越小越快，这是对的吗

**Comment by sustcsonglin** [comment]
如果head dimension不是很大的话，I/O cost不会很大。在这个情况下，chunk越小，并行度越高，所以越快是很有可能的。但通常为了达到更好的效果，head dimension会比较大，所以chunk越小可能I/O越大，并行带来的优势不如I/O的cost。这里面存在一个tradeoff。

**Comment by Joluck** [comment]
> 如果head dimension不是很大的话，I/O cost不会很大。在这个情况下，chunk越小，并行度越高，所以越快是很有可能的。但通常为了达到更好的效果，head dimension会比较大，所以chunk越小可能I/O越大，并行带来的优势不如I/O的cost。这里面存在一个tradeoff。

谢谢，bsz 8的情况chunk 16更快应该并行度不够，bsz拉大应该更适合128也会更快
