### ISSUE TITLE
Tips for training from scratch?

### ISSUE THREAD

**Issue by luchris429** [berlino/gated_linear_attention#8]
Hello,

I've been playing with this architecture on [nanoGPT](https://github.com/karpathy/nanoGPT/tree/master). While I can get other architectures to play nicely there (e.g. [RMT](https://github.com/lucidrains/recurrent-memory-transformer-pytorch)), I'm really struggling to get GLA to perform well.

Do you have any tips or code for training? For example, do you have a repository you recommend or key hyperparameter differences to normal transformers?

Thanks!

**Comment by sustcsonglin** [comment]
Hi, what is the model size and what is your current perf gap?

**Comment by luchris429** [comment]
~44M parameters. GLA is getting ~4 bpc (~2.7 nats), whereas RMT and Transformer can get ~1.4 bpc (~1.0 nats). 

I think the performance gap is big enough to suggest that something is very clearly not working though.

(Just launched another run that should have minimal differences in training setup -- can see that there's already significant divergence in training despite similar param count).

<img width="1376" alt="Screen Shot 2024-03-04 at 5 08 30 PM" src="https://github.com/berlino/gated_linear_attention/assets/6912913/cd53c9a7-421f-41ff-bc87-23440a8e705b">

**Comment by luchris429** [comment]
Are there any potential sharp bits for installation or setup that you've seen?

If it's useful to other people:

Small repo to test: [here](https://github.com/luchris429/nanoGPT/tree/master).

Code diff for including GLA (with exception of recent updates to nanoGPT): [here](https://linediff.com/?id=65e60071687f4bbb648b4569)

**Comment by sustcsonglin** [comment]
what is your triton version? can you pass [this test](https://github.com/sustcsonglin/flash-linear-attention/blob/main/tests/test_fused_chunk.py)

**Comment by luchris429** [comment]
Ahh that might be it! I'm on Triton 2.1.0

<img width="364" alt="Screen Shot 2024-03-04 at 6 35 39 PM" src="https://github.com/berlino/gated_linear_attention/assets/6912913/b1455678-951e-4da9-8b18-f1da5d765497">

Will upgrade triton and get back to you.

**Comment by luchris429** [comment]
Just upgraded -- Is this diff more reasonable or still too off?

<img width="362" alt="Screen Shot 2024-03-04 at 6 39 38 PM" src="https://github.com/berlino/gated_linear_attention/assets/6912913/af96c3d0-62c1-40a7-a8fd-8458671a68e5">

**Comment by sustcsonglin** [comment]
Looks normal! I think after the triton version update your gla training will be good

**Comment by sustcsonglin** [comment]
Also for smaller model, I would recommend the parameter allocation that is used in RetNet. i.e., d_key = d_model, d_value = 2*d_model. FFN expansion=2.

**Comment by yzhangcs** [comment]
@luchris429 Hi, please refer to this fix commit (https://github.com/sustcsonglin/flash-linear-attention/commit/84a3940ab99bccdf1e64e040b78f65d110516365). 
Sorry for wasting your time.

**Comment by luchris429** [comment]
It's doing better than Transformer now! Thanks so much @yzhangcs  @sustcsonglin ! Great work.

<img width="1381" alt="Screen Shot 2024-03-04 at 8 16 27 PM" src="https://github.com/berlino/gated_linear_attention/assets/6912913/63f9a5ef-2040-4d09-8a55-8f07adacc80d">
